version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: requirements/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:librarydb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    restart: unless-stopped
    networks:
      - library-network

networks:
  library-network:
    driver: bridge 